/*
*********************************************************
Apex Class Name    : CarrierAppointmentTriggerHandler
Created Date       : 2025-04-09
@description       : Handles logic for Carrier Appointment trigger events.
@author            : Uros Markovic
Modification Log:
Ver   Date         Author         Modification
1.0   2025-04-09   Uros Markovic  Initial Version
*********************************************************
*/
public with sharing class CarrierAppointmentTriggerHandler extends BaseTriggerHandler {
    // No trigger logic needed - LOA fields are now directly on CarrierAppointment
}